const TRANSLATIONS = {
  tr: {
    girisAdLabel: 'Adın',
    girisAdPlaceholder: 'Adını yaz',
    devamEt: 'Devam Et',
    veya: 'veya',
    googleGiris: 'Google ile Giriş Yap',
    googleGirisYapiliyor: 'Tarayıcıda giriş yapılıyor...',
    kanallarBaslik: 'KANALLAR',
    birKanalSec: 'Bir kanal seç',
    baglaniyor: 'Bağlanıyor...',
    baglanilamadi: 'Bağlanılamadı',
    yukleniyor: 'Yükleniyor...',
    kimseYok: 'Kimse yok',
    alinamadi: 'Alınamadı',
    mikrofonBaslik: 'Mikrofonu kapat/aç',
    ekranPaylasBaslik: 'Ekran paylaş',
    sesPaneliBaslik: 'Ses Paneli',
    sohbetAcKapatBaslik: 'Sohbeti göster/gizle',
    kanaldanAyrilBaslik: 'Kanaldan ayrıl',
    tamEkranBaslik: 'Tam ekran',
    ayarlarBaslik: 'Ayarlar',
    cikisYapBaslik: 'Çıkış yap',
    cevrimiciBaslik: 'Çevrimiçi',
    sekmeDonanim: 'Donanım',
    sekmeGorunum: 'Görünüm',
    sekmeKisayollar: 'Kısayollar',
    mikrofonLabel: 'Mikrofon',
    hoparlorLabel: 'Hoparlör',
    anaSesSeviyesi: 'Ana ses seviyesi',
    sesPaneliSesi: 'Ses Paneli Sesi',
    gurultuEngelleme: 'Gürültü Engelleme (Noise Cancellation)',
    yuksekSesSinirlayici: 'Yüksek Ses Sınırlayıcı (Limiter)',
    limiterAciklama: 'daha düşük = daha erken devreye girer',
    sesEsigiLabel: 'Ses Eşiği (Voice Activation)',
    sesEsigiAciklama: 'daha düşük = daha hassas',
    temaLabel: 'Tema',
    temaKoyu: '🌑 Koyu',
    temaAcik: '☀️ Açık',
    temaGeceMavisi: '🌌 Gece Mavisi',
    temaMor: '🟣 Mor',
    dilLabel: 'Dil',
    mikrofonAcKapatLabel: 'Mikrofon Aç/Kapat',
    yayinDurdurLabel: 'Yayını Durdur',
    kisayolAtanmadi: 'Atanmadı',
    kisayolTuslaraBas: 'Tuşlara bas...',
    kisayolTekrarDene: 'Tekrar dene',
    kisayolModifierUyari: '⚠️ Ctrl/Alt/Shift ile birlikte bas',
    kisayolBasarisiz: 'kullanılamıyor (başka uygulama kullanıyor olabilir)',
    kisayolNot: 'Bu kısayollar uygulama arka plandayken (başka pencerede) de çalışır.',
    kapat: 'Kapat',
    sesIsimPlaceholder: 'İsim (emoji olabilir, max 15 karakter)',
    ekle: 'Ekle',
    sesEklemeYukleniyor: 'Yükleniyor...',
    sesEklenemedi: 'Ses eklenemedi, tekrar dene.',
    sesUzunHata: 'saniye — en fazla 5 saniye olabilir.',
    sesGecersizDosya: 'Bu dosya okunamadı, geçerli bir ses dosyası seç.',
    neyiPaylas: 'Neyi paylaşmak istersin?',
    kaliteLabel: 'Kalite',
    vazgec: 'Vazgeç',
    mesajYaz: 'Mesaj yaz...',
    gonder: 'Gönder',
    girisHataAdYok: 'Lütfen adını yaz.',
    girisHataGoogle: 'Google ile giriş yapılamadı.',
    isimKullaniliyorUyari: 'ismi bu kanalda zaten kullanılıyor. Lütfen adını değiştir (çıkış yapıp tekrar gir).',
    baglanilamadiUyari: 'Bağlanılamadı. Token sunucusu adresini kontrol et.',
    guncellemeHazir: 'Yeni sürüm indirildi. Şimdi güncellemek için Tamam’a bas. Uygulama kapanıp güncellenecek.',
    sesUzunlukFazla: 'Bu ses',
    sen: '(sen)',
    izliyor: 'izliyor',
    yayinAcik: '🖥️ Yayın açık',
    yayinVarIzle: '🖥️ Yayın var · izle',
    bağlantıDurumu: '🟡 Bağlanıyor...',
    baglıDurum: '🟢 Bağlı',
    baglantıKesildi: '🔴 Bağlantı Kesildi',
    yenidenbağlanılıyor: '🟠 Yeniden Bağlanılıyor...',
    afkDurumu: '😴 AFK'
  },
  en: {
    girisAdLabel: 'Your Name',
    girisAdPlaceholder: 'Enter your name',
    devamEt: 'Continue',
    veya: 'or',
    googleGiris: 'Sign in with Google',
    googleGirisYapiliyor: 'Signing in via browser...',
    kanallarBaslik: 'CHANNELS',
    birKanalSec: 'Select a channel',
    baglaniyor: 'Connecting...',
    baglanilamadi: 'Could not connect',
    yukleniyor: 'Loading...',
    kimseYok: 'No one here',
    alinamadi: 'Could not load',
    mikrofonBaslik: 'Toggle microphone',
    ekranPaylasBaslik: 'Share screen',
    sesPaneliBaslik: 'Soundboard',
    sohbetAcKapatBaslik: 'Show/hide chat',
    kanaldanAyrilBaslik: 'Leave channel',
    tamEkranBaslik: 'Fullscreen',
    ayarlarBaslik: 'Settings',
    cikisYapBaslik: 'Log out',
    cevrimiciBaslik: 'Online',
    sekmeDonanim: 'Hardware',
    sekmeGorunum: 'Appearance',
    sekmeKisayollar: 'Shortcuts',
    mikrofonLabel: 'Microphone',
    hoparlorLabel: 'Speaker',
    anaSesSeviyesi: 'Master volume',
    sesPaneliSesi: 'Soundboard volume',
    gurultuEngelleme: 'Noise Suppression',
    yuksekSesSinirlayici: 'Loud Sound Limiter',
    limiterAciklama: 'lower = kicks in sooner',
    sesEsigiLabel: 'Voice Activation Threshold',
    sesEsigiAciklama: 'lower = more sensitive',
    temaLabel: 'Theme',
    temaKoyu: '🌑 Dark',
    temaAcik: '☀️ Light',
    temaGeceMavisi: '🌌 Midnight Blue',
    temaMor: '🟣 Purple',
    dilLabel: 'Language',
    mikrofonAcKapatLabel: 'Toggle Microphone',
    yayinDurdurLabel: 'Stop Screen Share',
    kisayolAtanmadi: 'Not set',
    kisayolTuslaraBas: 'Press keys...',
    kisayolTekrarDene: 'Try again',
    kisayolModifierUyari: '⚠️ Press with Ctrl/Alt/Shift',
    kisayolBasarisiz: 'unavailable (another app may be using it)',
    kisayolNot: 'These shortcuts also work when the app is in the background.',
    kapat: 'Close',
    sesIsimPlaceholder: 'Name (emoji ok, max 15 chars)',
    ekle: 'Add',
    sesEklemeYukleniyor: 'Uploading...',
    sesEklenemedi: 'Could not add sound, try again.',
    sesUzunHata: 'seconds — maximum is 5 seconds.',
    sesGecersizDosya: 'This file could not be read, pick a valid audio file.',
    neyiPaylas: 'What would you like to share?',
    kaliteLabel: 'Quality',
    vazgec: 'Cancel',
    mesajYaz: 'Type a message...',
    gonder: 'Send',
    girisHataAdYok: 'Please enter your name.',
    girisHataGoogle: 'Could not sign in with Google.',
    isimKullaniliyorUyari: 'is already taken in this channel. Please change your name (log out and back in).',
    baglanilamadiUyari: 'Could not connect. Check the token server address.',
    guncellemeHazir: 'A new version has been downloaded. Press OK to update now. The app will close and update itself.',
    sesUzunlukFazla: 'This sound is',
    sen: '(you)',
    izliyor: 'watching',
    yayinAcik: '🖥️ Live',
    yayinVarIzle: '🖥️ Stream available · watch'
  }
};

function t(anahtar) {
  const dil = (window.APP_AYARLAR && window.APP_AYARLAR.dil) || 'tr';
  return TRANSLATIONS[dil]?.[anahtar] ?? TRANSLATIONS.tr[anahtar] ?? anahtar;
}

function dilUygula(dilKodu) {
  window.APP_AYARLAR = window.APP_AYARLAR || {};
  window.APP_AYARLAR.dil = dilKodu;

  document.querySelectorAll('[data-i18n]').forEach((el) => {
    el.textContent = t(el.dataset.i18n);
  });
  document.querySelectorAll('[data-i18n-placeholder]').forEach((el) => {
    el.placeholder = t(el.dataset.i18nPlaceholder);
  });
  document.querySelectorAll('[data-i18n-title]').forEach((el) => {
    el.title = t(el.dataset.i18nTitle);
  });
}
